### ISSUE TITLE
Find Command doesn't work according to description

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-2/main#104]
**Describe the bug**
The find command does not work according to the User Guide examples provided

**To Reproduce**
1. Go to the main page of the application
2. Type in `find Charlotte Oliveiro` for example, the application throws `Invalid command format!`
3. Now, in your User Guide, scroll down to section `3.2.5. Locating persons by name: find`
4. According to the User Guide, an example of `find Charlotte Oliveiro` should match with the person in the addressbook.
5. This is the error

**Expected behavior**
`find Charlotte Oliveiro` should return the person in the list instead of giving an error.

**Screenshots**
Check the following image:
<img width="1276" alt="find command description" src="https://user-images.githubusercontent.com/32096360/47905451-2a547580-dec2-11e8-8182-2837ad559f90.png">

<hr>

**Reported by:** @aaryamnus
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#69]</sub>

**Comment by leegengyu** [comment]
Hello @aaryamNUS!

Thank you for your bug report regarding a **misrepresentation in our application versus our User Guide**.

I have looked into the bug as mentioned, and corrected the incorrect portions in the User Guide accordingly.
![image](https://user-images.githubusercontent.com/35021368/47948018-1f055680-df63-11e8-9a10-57a939099977.png)

We also acknowledge that there are
1. bugs with the **functionality of the find command** at the moment
2. **missing white-space for the example command** given in the application (should be "find main" instead of "findmain")

We will be fixing these bugs before the next release.

Thank you for your time in reporting this bug!

Geng Yu

**Comment by E0201942** [comment]
Duplicate issue
