### ISSUE TITLE
unclear if the the person should be searched automatically when select command is used

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-2/main#126]
**Describe the bug**
user guide says that it should load the google search page of the selected person but it does not

**To Reproduce**
1. enter 'select 1'
2. person gets selected but nothing happens

**Expected behavior**
should load google search page?

**Screenshots**
<img width="1429" alt="screenshot 2018-11-02 at 17 35 32" src="https://user-images.githubusercontent.com/35647345/47907405-29bdde00-dec6-11e8-95c7-ba45a6f4a708.png">
<img width="989" alt="screenshot 2018-11-02 at 17 36 18" src="https://user-images.githubusercontent.com/35647345/47907406-29bdde00-dec6-11e8-90c8-7d1aaa9bf8f5.png">

**Additional context**
good job tho 

<hr>

**Reported by:** @kianmengtan
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#448]</sub>

**Comment by leegengyu** [comment]
Hello @kianmengtan!

Thank you for your bug report regarding a **mismatch in functionality for our select command**.

I have edited the User Guide to show that work is in progress, and also because we **need to fix our select command** as well:
![image](https://user-images.githubusercontent.com/35021368/47948496-38ab9b80-df6d-11e8-9dc9-81e24270b2de.png)

Thank you for your time in reporting this bug!

Geng Yu

**Comment by E0201942** [comment]
Select command has been fixed
