### ISSUE TITLE
Section 3.4 of the User Guide should be formatted

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-2/main#128]
**Please describe the problem**
Section `3.4` is still in the User Guide despite it not being functional. 

**Describe the improvement you'd like to suggest**
Perhaps you can remove this section or have a tag such as `Coming in v2.0` when you find a workaround, just so that the user doesn't accidentally test out these commands and input sensitive information such as the `password`

<hr>

**Reported by:** @aaryamnus
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#547]</sub>

**Comment by leegengyu** [comment]
Hello @aaryamNUS!

Thank you for your bug report regarding our **non-functional notes command**.

We acknowledge that it would have been better to leave it out of the User Guide altogether because we are unable to run the function for this PE, but because we have been advised to leave it in the UG tentatively.

Nonetheless, we have included a paragraph at the start of Section 3.4 - but we acknowledge that it could have been **made more noticeable to users because they should be clearly made aware of it**.

If we are required to leave it in our User Guide (despite non-functionality), we will make it clearer and more noticeable to users that this is the case. Else, we will remove it altogether the next time.

Thank you for your time in reporting this bug!

Geng Yu

**Comment by ABearPerson** [comment]
Its functional, You are able to view notes, and login, Download is disabled for reasons stated.
